name: Validate WinGet DSC Packages (REST)
description: Validate Microsoft.WinGet.DSC WinGetPackage IDs using WinGet REST API (no winget.exe)

inputs:
  dscfile:
    description: Path to DSC YAML file
    required: true

runs:
  using: composite
  steps:
    - name: Validate WinGet packages via REST
      shell: pwsh
      run: |
        & (Join-Path $env:GITHUB_ACTION_PATH 'scripts/validate-winget-dsc-api.ps1') -DscFile "${{ inputs.dscfile }}"

        
    - name: Validate msstore WinGet packages via WinGet Client
      shell: pwsh
      run: |
        & (Join-Path $env:GITHUB_ACTION_PATH 'scripts/validate-winget-dsc-msstore.ps1') -DscFile "${{ inputs.dscfile }}" -WinGetClientNuPkg (Join-Path $env:GITHUB_ACTION_PATH 'packages/Microsoft.WinGet.Client.0.2.1.nupkg')
        
