name: "Parse JSONC"
description: "Parse a JSONC file and expose values as outputs"
author: "Ronny Van Dessel"

inputs:
  path:
    description: "Path to the JSONC file"
    required: true

outputs:
  targets_r0:
    description: "Targets_R0 value from JSONC"
    value: ${{ steps.parse.outputs.targets_r0 }}

  lines_count:
    description: "Number of lines in data.txt"
    value: ${{ steps.parse.outputs.lines_count }}



runs:
  using: "composite"
  steps:
    - name: Parse JSONC
      id: parse
      shell: pwsh
      run: |
        $scriptPath = Join-Path "${{ github.action_path }}" "scripts\parse-json.ps1"

        Write-Host "Action path: ${{ github.action_path }}"
        Write-Host "Resolved script path: $scriptPath"

        if (-not (Test-Path $scriptPath)) {
          Write-Error "Script not found at $scriptPath"
          Get-ChildItem -Recurse "${{ github.action_path }}"
          exit 1
        }

        & $scriptPath -Path "${{ inputs.path }}"
